In [1]:
import numpy as np
import pandas as pd

In [25]:
pd.set_option("display.max_rows" ,None)
pd.set_option("display.max_columns" ,None)

In [26]:
data = pd.read_csv("/content/Retail_Dataset_Modified.csv")
data

Output hidden; open in https://colab.research.google.com to view.

In [30]:
data.select_dtypes(include='object').head(4)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,Quantity_Available,Units_Sold,Revenue,Customer_Segment,Sales_Channel,Payment_Method,Supplier,Supplier_Rating,Promotion_Type,Return_Reason,Competition_Level,Price_Competitiveness,Weather_Impact,Shipping_Cost,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,125,24,7320,Budget,BrandX_India Online,UPI,BrandX_India E-commerce Hub,Nan,Festival Offer,Wrong Size,Medium,Standard,Low,57,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,135,35,1645,Luxury,BrandX_India Online,UPI,BrandX_India Direct Import,Nan,Clearance,Poor Quality,High,Competitive,Low,99,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,215,31,66340,Mid-Range,BrandX_India Online,Wallet,BrandX_India Local Sourcing,Nan,Clearance,Wrong Size,Medium,Standard,Medium,101,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,163,22,77748,Premium,BrandX_India App,Card,BrandX_India Direct Import,Nan,Flash Sale,Wrong Size,High,Competitive,Medium,79,Q1,Spring

In [31]:
data["Unit_Price"] = pd.to_numeric(data["Unit_Price"])

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   object
 1   Store_Name             5171 non-null   object
 2   Brand_Name             5171 non-null   object
 3   Store_Type             5171 non-null   object
 4   City                   5109 non-null   object
 5   City_Tier              5171 non-null   object
 6   Product_Name           5098 non-null   object
 7   Category               5171 non-null   object
 8   Sub_Category           5171 non-null   object
 9   Product_Stage          5171 non-null   object
 10  Quantity_Available     5171 non-null   object
 11  Units_Sold             5171 non-null   object
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   object
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   object
 20  Sales_Channel          5171 non-null   object
 21  Payment_Method         5171 non-null   object
 22  Supplier               5103 non-null   object
 23  Supplier_Rating        5171 non-null   object
 24  Promotion_Type         5171 non-null   object
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   object
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   object
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   object
 40  Weather_Impact         5171 non-null   object
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   object
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   object
 46  Season                 5171 non-null   object
dtypes: float64(11), int64(10), object(26)
memory usage: 1.9+ MB

In [4]:
data.describe()

,Unit_Price,Cost_Price,Profit_Margin,Average_Order_Value,Inventory_Turnover,Days_of_Stock,Promotion_Impact,Max_Discount_Offered,Return_Rate,Customer_Satisfaction,...,Review_Count,Sales_Rep_Experience,Sales_Rep_Rating,Market_Share,Competitor_Count,Brand_Loyalty,Brand_Awareness,Delivery_Time,Month,Year
count,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5094.000000,...,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5111.000000,5171.000000,5171.000000
mean,36147.283117,28008.718236,22.455080,45000.251789,3.928517,142.718816,20.979791,22.679172,4.018294,4.209109,...,256.498936,5.548250,4.248018,15.406556,16.231483,81.351228,80.307097,3.984934,6.567588,2023.016438
std,53910.395954,41848.286241,4.349469,67405.809814,2.284159,128.281114,12.212204,15.784690,2.292903,0.280465,...,140.948535,2.861696,0.433274,6.009766,6.646939,8.018098,8.542352,2.021598,3.463351,0.814235
min,36.000000,28.000000,14.680000,41.000000,0.300000,32.000000,0.000000,0.000000,0.000000,3.600000,...,10.000000,1.000000,3.500000,3.000000,3.000000,67.000000,60.000000,1.000000,1.000000,2022.000000
25%,2016.500000,1548.500000,18.675000,2476.000000,2.220000,68.000000,13.100000,9.000000,2.000000,4.000000,...,138.000000,3.000000,3.900000,11.300000,11.000000,75.900000,77.700000,2.000000,4.000000,2022.000000
50%,11816.000000,9136.000000,22.450000,14734.000000,3.440000,105.000000,22.300000,22.000000,4.100000,4.200000,...,256.000000,6.000000,4.200000,14.900000,18.000000,80.400000,83.000000,4.000000,7.000000,2023.000000
75%,53778.500000,41569.000000,26.235000,66630.000000,5.260000,162.000000,31.200000,36.000000,6.000000,4.400000,...,378.000000,8.000000,4.600000,18.900000,22.000000,84.600000,86.600000,6.000000,10.000000,2024.000000
max,307651.000000,252171.000000,30.430000,450890.000000,11.100000,1200.000000,40.000000,50.000000,8.000000,4.900000,...,500.000000,10.000000,5.000000,30.000000,25.000000,100.000000,90.000000,7.000000,12.000000,2024.000000

In [19]:
print("Sample std :" , data["Unit_Price"].std(ddof= 1))
print("Population std :" , data["Unit_Price"].std(ddof= 0))

Sample std : 53910.39595393598
Population std : 53905.18293879504

In [20]:
print("Sample varr :" , data["Unit_Price"].var(ddof= 1))
print("Population varr :" , data["Unit_Price"].var(ddof= 0))

Sample varr : 2906330791.9101567
Population varr : 2905768747.6649604

In [21]:
data["Unit_Price"].mean()

np.float64(36147.28311738542)

In [22]:
data["Unit_Price"].median()

11816.0

In [5]:
data.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [7]:
data["Store_Type"].unique()

array(['Flagship', 'Street Store', 'Mall Store', 'Express', 'Online Hub'],
      dtype=object)

In [9]:
sorted(data["Store_Type"].unique())

['Express', 'Flagship', 'Mall Store', 'Online Hub', 'Street Store']

In [6]:
data2 = data.sort_values(by='Store_Type')
data2

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
3352,BX_AHMEDABAD_015,BrandX_India Style Ahmedabad,BrandX_India,Express,Ahmedabad,Tier1,Adidas Ultraboost,Clothes,Shoes,Mature,...,69.6,75.0,Competitive,Medium,3.0,100,12,2023,Q4,Winter
1018,BX_CHENNAI_022,BrandX_India Accessories Chennai,BrandX_India,Express,Chennai,Metro,Canon EOS R6,Gadgets,Cameras,Declining,...,78.5,82.4,Competitive,Low,4.0,60,8,2022,Q3,Monsoon
1016,BX_DELHI_004,BrandX_India Home Delhi,BrandX_India,Express,Delhi,Metro,LG Double Door 260L,Home Appliances,Refrigerators,Mature,...,84.3,88.1,Aggressive,Low,7.0,743,8,2022,Q3,Monsoon
1012,BX_BHOPAL_032,BrandX_India Tech Hub Bhopal,BrandX_India,Express,Bhopal,Tier2,iPhone 14,Electronics,Smartphones,Mature,...,83.2,68.1,Standard,Low,3.0,281,8,2022,Q3,Monsoon
3042,BX_CHENNAI_093,BrandX_India Trends Chennai,BrandX_India,Express,Chennai,Metro,Levi's T-Shirt,Clothes,T-Shirts,Growing,...,76.5,88.5,Competitive,Medium,2.0,135,10,2023,Q4,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1137,BX_LUCKNOW_076,BrandX_India Fashion Lucknow,BrandX_India,Street Store,Lucknow,Tier2,Nike Air Max,Clothes,Shoes,Declining,...,67.9,65.0,Standard,Medium,3.0,87,9,2022,Q3,Monsoon
2782,BX_AHMEDABAD_068,BrandX_India Apparel Ahmedabad,BrandX_India,Street Store,Ahmedabad,Tier1,Pepe Jeans,Clothes,Jeans,Discontinued,...,75.9,75.0,Competitive,Medium,7.0,102,8,2023,Q3,Monsoon
2783,BX_PUNE_037,BrandX_India Smart Pune,BrandX_India,Street Store,Pune,Tier1,Bose SoundLink,Gadgets,Bluetooth Speakers,Discontinued,...,76.6,81.2,Competitive,Low,7.0,89,8,2023,Q3,Monsoon
1145,BX_DELHI_054,BrandX_India Digital Delhi,BrandX_India,Street Store,Delhi,Metro,Sony WH-1000XM5,Electronics,Headphones,Mature,...,76.5,83.3,Aggressive,Low,3.0,138,9,2022,Q3,Monsoon
826,BX_SURAT_044,BrandX_India Trends Surat,BrandX_India,Street Store,Surat,Tier2,H&M Cotton Tee,Clothes,T-Shirts,Discontinued,...,77.0,69.5,Standard,Medium,5.0,102,7,2022,Q3,Monsoon

In [10]:
data3 = data.sort_values(by='Store_Type' , ascending= False)
data3

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
4761,BX_PUNE_079,BrandX_India Digital Pune,BrandX_India,Street Store,Pune,Tier1,Dell XPS 13,Electronics,Laptops,Mature,...,69.5,74.0,Standard,Low,5.0,268,10,2024,Q4,Winter
937,BX_CHENNAI_078,BrandX_India Tech Hub Chennai,BrandX_India,Street Store,Chennai,Metro,Sony WH-1000XM5,Electronics,Headphones,Declining,...,97.4,81.3,Competitive,Low,2.0,163,8,2022,Q3,Monsoon
2294,BX_PUNE_099,BrandX_India Appliances Pune,BrandX_India,Street Store,Pune,Tier1,Samsung 23L Solo,Home Appliances,Microwaves,Discontinued,...,82.9,77.8,Competitive,High,5.0,214,5,2023,Q2,Summer
4692,BX_DELHI_005,BrandX_India Style Delhi,BrandX_India,Street Store,Delhi,Metro,Nike Air Max,Clothes,Shoes,Discontinued,...,77.6,81.1,Competitive,Medium,2.0,58,9,2024,Q3,Monsoon
2296,BX_SURAT_058,BrandX_India Digital Surat,BrandX_India,Street Store,Surat,Tier2,Sony WH-1000XM5,Electronics,Headphones,Growing,...,76.9,61.7,Standard,Low,4.0,210,5,2023,Q2,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4164,BX_MUMBAI_029,BrandX_India Smart Mumbai,BrandX_India,Express,Mumbai,Metro,Sony Alpha a7 IV,Gadgets,Cameras,Mature,...,82.4,80.2,Competitive,Low,2.0,109,6,2024,Q2,Monsoon
2033,BX_MUMBAI_046,BrandX_India Style Mumbai,BrandX_India,Express,Mumbai,Metro,Levi's T-Shirt,Clothes,T-Shirts,New Launch,...,96.8,84.3,Competitive,Medium,4.0,93,3,2023,Q1,Summer
2034,BX_PUNE_076,BrandX_India Gadget Zone Pune,BrandX_India,Express,Pune,Tier1,AirPods Pro,Electronics,Headphones,Declining,...,69.2,78.5,Competitive,Low,6.0,194,3,2023,Q1,Summer
4161,BX_BANGALORE_033,BrandX_India Trends Bangalore,BrandX_India,Express,Bangalore,Metro,Levi's T-Shirt,Clothes,T-Shirts,Discontinued,...,76.2,82.9,Competitive,High,1.0,102,6,2024,Q2,Monsoon
4306,BX_DELHI_061,BrandX_India Gadget Zone Delhi,BrandX_India,Express,Delhi,Metro,MacBook Air M2,Electronics,Laptops,New Launch,...,75.7,84.9,Competitive,Low,3.0,123,7,2024,Q3,Monsoon

In [11]:
data.select_dtypes(exclude='object')

,Unit_Price,Cost_Price,Profit_Margin,Average_Order_Value,Inventory_Turnover,Days_of_Stock,Promotion_Impact,Max_Discount_Offered,Return_Rate,Customer_Satisfaction,...,Review_Count,Sales_Rep_Experience,Sales_Rep_Rating,Market_Share,Competitor_Count,Brand_Loyalty,Brand_Awareness,Delivery_Time,Month,Year
0,305,239,21.64,432,2.30,156,23.1,9,3.1,4.0,...,53,5,4.8,15.3,8,70.8,75.7,6.0,1,2022
1,47,33,29.79,63,3.11,116,34.9,21,2.9,3.9,...,202,10,3.6,18.9,25,80.5,81.5,4.0,1,2022
2,2140,1715,19.86,2994,1.73,208,29.4,36,6.3,4.3,...,77,1,4.0,14.2,11,68.5,76.7,4.0,1,2022
3,3534,2894,18.11,4416,1.62,222,37.3,31,4.0,4.4,...,221,7,3.9,16.4,19,92.4,88.0,5.0,1,2022
4,50676,40467,20.15,54629,2.80,128,33.1,43,4.8,3.9,...,205,6,4.9,13.4,19,82.9,89.5,2.0,1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,2373,1972,16.90,2617,0.45,797,37.9,48,7.9,4.2,...,368,6,4.9,10.9,7,91.3,68.7,3.0,11,2024
5167,54,43,20.37,58,3.85,93,34.5,13,5.0,3.7,...,424,3,4.8,14.1,21,81.6,82.0,7.0,7,2023
5168,75554,52990,29.86,94881,1.77,203,0.0,0,5.3,3.9,...,326,6,3.8,11.3,6,89.9,68.1,1.0,7,2023
5169,11102,9267,16.53,16105,1.61,224,29.1,30,4.0,4.4,...,73,1,3.6,12.5,17,80.6,86.5,3.0,12,2022
5170,117390,82950,29.34,166575,0.75,480,0.0,0,6.9,4.7,...,500,1,4.4,27.2,18,91.8,85.0,3.0,6,2024

In [13]:
data.nlargest(4,"Unit_Price")

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
2458,BX_BANGALORE_029,BrandX_India Accessories Bangalore,BrandX_India,Online Hub,Bangalore,Metro,Sony Alpha a7 IV,Gadgets,Cameras,Discontinued,...,77.1,87.4,Aggressive,Low,1.0,90,6,2023,Q2,Monsoon
4584,BX_BANGALORE_078,BrandX_India Accessories Bangalore,BrandX_India,Mall Store,Bangalore,Metro,Sony Alpha a7 IV,Gadgets,Cameras,Mature,...,82.8,80.1,Aggressive,Low,3.0,133,9,2024,Q3,Monsoon
4765,BX_MUMBAI_041,BrandX_India Mobile Mumbai,BrandX_India,Street Store,Mumbai,Metro,Sony Alpha a7 IV,Gadgets,Cameras,Growing,...,78.3,81.5,Aggressive,Low,3.0,142,10,2024,Q4,Winter
1099,BX_HYDERABAD_058,BrandX_India Smart Hyderabad,BrandX_India,Online Hub,Hyderabad,Metro,Sony Alpha a7 IV,Gadgets,Cameras,New Launch,...,81.9,89.3,Aggressive,Low,2.0,65,9,2022,Q3,Monsoon

In [15]:
data.nsmallest(4,"Unit_Price")

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
3497,BX_NAGPUR_054,BrandX_India Superstore Nagpur,BrandX_India,Express,Nagpur,Tier2,White Sugar 1kg,Groceries,Sugar,Growing,...,87.5,61.0,Standard,Low,2.0,52,1,2024,Q1,Spring
4756,BX_SURAT_080,BrandX_India Superstore Surat,BrandX_India,Street Store,Surat,Tier2,White Sugar 1kg,Groceries,Sugar,Declining,...,73.8,67.0,Standard,Low,7.0,115,10,2024,Q4,Winter
1054,BX_JAIPUR_059,BrandX_India Superstore Jaipur,BrandX_India,Street Store,Jaipur,Tier2,White Sugar 1kg,Groceries,Sugar,Declining,...,83.0,66.5,Standard,Low,7.0,134,8,2022,Q3,Monsoon
214,BX_SURAT_054,BrandX_India Fresh Surat,BrandX_India,Flagship,Surat,Tier2,White Sugar 1kg,Groceries,Sugar,Discontinued,...,72.1,68.5,Standard,Low,5.0,85,2,2022,Q1,Spring